name: Manhunt
version: '${project.version}'
main: me.unleqitq.manhunt.Manhunt
api-version: 1.17
load: STARTUP
softdepend: [ PlaceholderAPI ]
authors: [ UnleqitQ ]
commands:
  manhunt:
    description: Manhunt
